### ISSUE TITLE
Save the signatures uncovered by the pipeline 

### ISSUE THREAD

**Issue by josephineyates** [BoevaLab/CanSig#33]
Since our pipeline's ultimate goal is to discover de novo signatures that are meaningful, we want to save the signatures found in each folder

**Comment by pawel-czyz** [comment]
How is it different from #16 ?

**Comment by josephineyates** [comment]
#16 saves the results of GSEA, this saves the results of the differential gene expression, meaning here we only save for every cluster the list of differentially expressed genes with associated p value, while for the GSEA results we save the enrichment pathways found
